### ISSUE TITLE
Some packets bypassing the user defined filter?

### ISSUE THREAD

**Issue by net2use** [hessu/aprsc#67]
Hello,

I've some clients (arpx 2.9) which set an user defined filter "r/49.6780/12.160/20", but the server (aprsc 2.1.10) sends packets outside the definied ranges. Now I tried to expand filter to block this packets "r/49.6780/12.160/20 -t/t -p/CW/DW -u/APRARX/APLWS*/APMI0*". But the filter didn't match to the unwanted packets.

I attach a text file with the packets which bypass the following filter: "r/49.6780/12.160/20 r/49.5570/12.4060/15 -t/t -p/CW/DW -u/APRARX/APLWS*/APMI0*"

Is it a bug or it's my fail?

Thank you and a happy new year!

Tom

[bypassfilter.txt](https://github.com/hessu/aprsc/files/7793125/bypassfilter.txt)

**Comment by hessu** [comment]
Hello,

The APRS-IS servers send out some additional packets so that clients can implement TX iGate features properly. These can not be filtered out.

http://www.aprs-is.net/IGateDetails.aspx says "Gate message packets and associated posits to RF if all of the following are true:" ... "4. the receiving station has not been heard via the Internet within a predefined time period."

For this to work, the APRS-IS server needs to send some packets to the igates: the APRS-IS server tracks the stations heard by the iGate, and sends any packets that were originated by those stations on the Internet side to the iGate.
